[package]
name = "errorfunctions"
version = "0.1.0"
edition = "2021"

[dependencies]

num = "0.4"
num-traits = "0.2"

[package.metadata.docs.rs]
rustdoc-args = [ "--html-in-header", "./src/html/docs-header.html" ]

